import { BaseNpmProvider } from './base-npm-provider.js';

/**
 * Bootstrap Icons Provider
 *
 * Provides access to Bootstrap Icons - official open source SVG icon library for Bootstrap
 * through NPM package integration.
 */
export class BootstrapIconsProvider extends BaseNpmProvider {
  constructor() {
    super(
      'bootstrap-icons',
      'Bootstrap Icons',
      '1.11.3',
      'bootstrap-icons',
      ['icons/*.svg'],
      ['regular']
    );
  }

  protected getDescription(): string {
    return 'Official open source SVG icon library for Bootstrap with over 1,800+ icons designed to work perfectly with Bootstrap components.';
  }

  protected getSourceUrl(): string {
    return 'https://github.com/twbs/icons';
  }

  protected getLicense(): string {
    return 'MIT';
  }

  /**
   * Override tag generation for Bootstrap Icons specific patterns
   */
  protected generateTags(iconName: string): string[] {
    const tags = new Set(super.generateTags(iconName));

    // Add Bootstrap specific tags
    tags.add('bootstrap');
    tags.add('twbs');
    tags.add('bi');

    // Bootstrap Icons specific synonyms
    const bootstrapSynonyms: Record<string, string[]> = {
      alarm: ['clock', 'time', 'alert'],
      app: ['application', 'software', 'program'],
      archive: ['box', 'storage', 'backup'],
      arrow: ['direction', 'pointer', 'navigation'],
      'aspect-ratio': ['resize', 'scale', 'proportion'],
      award: ['trophy', 'prize', 'achievement'],
      badge: ['label', 'tag', 'marker'],
      bag: ['shopping', 'purchase', 'carry'],
      bank: ['finance', 'money', 'institution'],
      'bar-chart': ['graph', 'statistics', 'data'],
      basket: ['shopping', 'cart', 'container'],
      battery: ['power', 'energy', 'charge'],
      bell: ['notification', 'alert', 'ring'],
      bicycle: ['bike', 'transport', 'vehicle'],
      binoculars: ['view', 'search', 'observe'],
      bookmark: ['save', 'favorite', 'mark'],
      bootstrap: ['framework', 'css', 'ui'],
      box: ['package', 'container', 'storage'],
      briefcase: ['work', 'business', 'job'],
      broadcast: ['radio', 'signal', 'transmission'],
      brush: ['paint', 'design', 'art'],
      bucket: ['container', 'storage', 'fill'],
      bug: ['insect', 'error', 'debug'],
      building: ['structure', 'office', 'architecture'],
      bullseye: ['target', 'aim', 'goal'],
      calculator: ['math', 'compute', 'numbers'],
      calendar: ['date', 'schedule', 'time'],
      camera: ['photo', 'picture', 'capture'],
      capslock: ['keyboard', 'caps', 'uppercase'],
      card: ['credit', 'payment', 'id'],
      cart: ['shopping', 'purchase', 'ecommerce'],
      cash: ['money', 'currency', 'payment'],
      cast: ['broadcast', 'stream', 'airplay'],
      chat: ['message', 'conversation', 'talk'],
      check: ['tick', 'confirm', 'done'],
      chevron: ['arrow', 'direction', 'expand'],
      circle: ['round', 'dot', 'shape'],
      clipboard: ['copy', 'paste', 'notes'],
      clock: ['time', 'schedule', 'timer'],
      cloud: ['storage', 'sync', 'weather'],
      code: ['programming', 'development', 'script'],
      collection: ['group', 'set', 'library'],
      compass: ['direction', 'navigation', 'guide'],
      cpu: ['processor', 'chip', 'computer'],
      'credit-card': ['payment', 'money', 'finance'],
      cup: ['coffee', 'drink', 'beverage'],
      cursor: ['pointer', 'mouse', 'click'],
      dash: ['line', 'minus', 'hyphen'],
      database: ['storage', 'data', 'server'],
      device: ['hardware', 'gadget', 'electronics'],
      diagram: ['chart', 'flow', 'structure'],
      diamond: ['gem', 'shape', 'precious'],
      dice: ['game', 'random', 'chance'],
      disc: ['cd', 'dvd', 'storage'],
      display: ['screen', 'monitor', 'show'],
      door: ['entrance', 'exit', 'access'],
      download: ['save', 'import', 'get'],
      droplet: ['water', 'liquid', 'drop'],
      ear: ['hearing', 'listen', 'audio'],
      easel: ['art', 'painting', 'canvas'],
      egg: ['food', 'breakfast', 'oval'],
      eject: ['remove', 'expel', 'exit'],
      emoji: ['emotion', 'face', 'expression'],
      envelope: ['mail', 'email', 'message'],
      eraser: ['delete', 'remove', 'clear'],
      exclamation: ['warning', 'alert', 'important'],
      eye: ['view', 'see', 'visibility'],
      eyedropper: ['color', 'picker', 'sample'],
      eyeglasses: ['glasses', 'vision', 'spectacles'],
      file: ['document', 'paper', 'text'],
      film: ['movie', 'video', 'cinema'],
      filter: ['sort', 'organize', 'refine'],
      flag: ['marker', 'country', 'banner'],
      flower: ['nature', 'plant', 'bloom'],
      folder: ['directory', 'collection', 'group'],
      fonts: ['typography', 'text', 'typeface'],
      forward: ['next', 'arrow', 'continue'],
      fuel: ['gas', 'energy', 'power'],
      funnel: ['filter', 'sort', 'narrow'],
      gear: ['settings', 'configuration', 'cog'],
      gem: ['diamond', 'precious', 'jewel'],
      geo: ['location', 'map', 'geography'],
      gift: ['present', 'reward', 'bonus'],
      globe: ['world', 'earth', 'international'],
      graph: ['chart', 'data', 'statistics'],
      grid: ['layout', 'table', 'matrix'],
      hammer: ['tool', 'build', 'construction'],
      hand: ['gesture', 'point', 'touch'],
      handbag: ['purse', 'bag', 'accessory'],
      hash: ['hashtag', 'number', 'pound'],
      hdd: ['hard-drive', 'storage', 'disk'],
      headphones: ['audio', 'music', 'sound'],
      headset: ['audio', 'communication', 'support'],
      heart: ['love', 'like', 'favorite'],
      hexagon: ['shape', 'geometry', 'six-sided'],
      hourglass: ['time', 'wait', 'loading'],
      house: ['home', 'building', 'residence'],
      hr: ['human-resources', 'people', 'staff'],
      hurricane: ['storm', 'weather', 'wind'],
      image: ['picture', 'photo', 'graphic'],
      inbox: ['mail', 'messages', 'receive'],
      incognito: ['private', 'anonymous', 'hidden'],
      infinity: ['endless', 'unlimited', 'forever'],
      info: ['information', 'help', 'about'],
      input: ['form', 'field', 'entry'],
      instagram: ['social', 'photo', 'sharing'],
      intersect: ['overlap', 'cross', 'merge'],
      journal: ['diary', 'notebook', 'writing'],
      joystick: ['game', 'controller', 'gaming'],
      kanban: ['board', 'project', 'organize'],
      key: ['password', 'security', 'access'],
      keyboard: ['typing', 'input', 'keys'],
      ladder: ['climb', 'steps', 'ascend'],
      lamp: ['light', 'illumination', 'bulb'],
      laptop: ['computer', 'portable', 'notebook'],
      layers: ['stack', 'levels', 'depth'],
      layout: ['design', 'structure', 'arrangement'],
      'life-preserver': ['safety', 'rescue', 'help'],
      lightbulb: ['idea', 'innovation', 'bright'],
      lightning: ['fast', 'quick', 'energy'],
      link: ['chain', 'connect', 'url'],
      list: ['items', 'menu', 'index'],
      lock: ['secure', 'private', 'protected'],
      magic: ['wand', 'spell', 'mystical'],
      magnet: ['attract', 'magnetic', 'pull'],
      mailbox: ['post', 'delivery', 'mail'],
      map: ['location', 'navigation', 'geography'],
      mask: ['face', 'protection', 'disguise'],
      megaphone: ['announce', 'broadcast', 'loud'],
      memory: ['ram', 'storage', 'computer'],
      menu: ['hamburger', 'navigation', 'options'],
      mic: ['microphone', 'voice', 'record'],
      minecart: ['mining', 'transport', 'cart'],
      modem: ['internet', 'connection', 'network'],
      moisture: ['humidity', 'water', 'damp'],
      moon: ['night', 'dark', 'lunar'],
      mouse: ['computer', 'click', 'pointer'],
      music: ['audio', 'sound', 'song'],
      newspaper: ['news', 'article', 'media'],
      node: ['network', 'connection', 'point'],
      nut: ['bolt', 'hardware', 'fastener'],
      octagon: ['shape', 'stop', 'eight-sided'],
      option: ['choice', 'select', 'alternative'],
      outlet: ['power', 'electricity', 'plug'],
      'paint-bucket': ['fill', 'color', 'design'],
      palette: ['color', 'art', 'design'],
      paperclip: ['attach', 'clip', 'link'],
      patch: ['fix', 'repair', 'update'],
      pause: ['stop', 'break', 'halt'],
      peace: ['harmony', 'calm', 'tranquil'],
      pen: ['write', 'edit', 'draw'],
      pencil: ['write', 'edit', 'draw'],
      pentagon: ['shape', 'five-sided', 'military'],
      people: ['users', 'group', 'team'],
      percent: ['percentage', 'ratio', 'proportion'],
      person: ['user', 'individual', 'human'],
      phone: ['call', 'telephone', 'mobile'],
      'pie-chart': ['graph', 'statistics', 'data'],
      'piggy-bank': ['savings', 'money', 'finance'],
      pin: ['location', 'marker', 'attach'],
      play: ['start', 'begin', 'media'],
      plug: ['power', 'electricity', 'connect'],
      plus: ['add', 'create', 'new'],
      power: ['on-off', 'electricity', 'energy'],
      printer: ['print', 'output', 'paper'],
      puzzle: ['game', 'solve', 'piece'],
      question: ['help', 'unknown', 'query'],
      quiver: ['arrows', 'archery', 'container'],
      radioactive: ['nuclear', 'danger', 'toxic'],
      rainbow: ['color', 'spectrum', 'weather'],
      receipt: ['bill', 'invoice', 'payment'],
      reception: ['signal', 'bars', 'strength'],
      record: ['vinyl', 'music', 'audio'],
      recycle: ['reuse', 'environment', 'green'],
      reply: ['respond', 'answer', 'back'],
      rewind: ['back', 'previous', 'reverse'],
      robot: ['automation', 'ai', 'machine'],
      rocket: ['launch', 'space', 'fast'],
      router: ['network', 'wifi', 'internet'],
      rss: ['feed', 'news', 'subscribe'],
      rulers: ['measure', 'length', 'scale'],
      safe: ['security', 'vault', 'protection'],
      save: ['disk', 'store', 'keep'],
      scissors: ['cut', 'trim', 'clip'],
      screwdriver: ['tool', 'fix', 'repair'],
      search: ['find', 'look', 'magnify'],
      'segmented-nav': ['tabs', 'navigation', 'menu'],
      server: ['database', 'hosting', 'cloud'],
      share: ['distribute', 'send', 'export'],
      shield: ['security', 'protection', 'safe'],
      shift: ['keyboard', 'uppercase', 'modify'],
      shop: ['store', 'shopping', 'retail'],
      shuffle: ['random', 'mix', 'rearrange'],
      signpost: ['direction', 'guide', 'navigation'],
      sim: ['card', 'mobile', 'phone'],
      skip: ['next', 'forward', 'jump'],
      slash: ['divide', 'separate', 'line'],
      sliders: ['controls', 'settings', 'adjust'],
      smartwatch: ['watch', 'wearable', 'time'],
      snow: ['weather', 'winter', 'cold'],
      sort: ['order', 'arrange', 'organize'],
      soundwave: ['audio', 'frequency', 'sound'],
      speaker: ['audio', 'sound', 'volume'],
      speedometer: ['speed', 'gauge', 'performance'],
      star: ['favorite', 'rating', 'bookmark'],
      stickies: ['notes', 'sticky', 'reminder'],
      stop: ['halt', 'pause', 'end'],
      stopwatch: ['timer', 'time', 'measure'],
      subtract: ['minus', 'remove', 'less'],
      suit: ['cards', 'playing', 'game'],
      sun: ['day', 'light', 'bright'],
      sunrise: ['morning', 'dawn', 'early'],
      sunset: ['evening', 'dusk', 'late'],
      symmetry: ['balance', 'equal', 'mirror'],
      table: ['grid', 'data', 'spreadsheet'],
      tablet: ['device', 'mobile', 'screen'],
      tag: ['label', 'category', 'mark'],
      taxi: ['cab', 'transport', 'vehicle'],
      telephone: ['phone', 'call', 'communication'],
      terminal: ['console', 'command', 'cli'],
      text: ['typography', 'font', 'writing'],
      thermometer: ['temperature', 'heat', 'measure'],
      'three-dots': ['more', 'menu', 'options'],
      thunderstorm: ['storm', 'weather', 'lightning'],
      ticket: ['pass', 'entry', 'voucher'],
      toggle: ['switch', 'on-off', 'flip'],
      tools: ['utilities', 'repair', 'fix'],
      tornado: ['storm', 'weather', 'wind'],
      translate: ['language', 'convert', 'international'],
      trash: ['delete', 'remove', 'bin'],
      tree: ['nature', 'plant', 'growth'],
      triangle: ['shape', 'three-sided', 'geometry'],
      trophy: ['award', 'prize', 'achievement'],
      truck: ['delivery', 'shipping', 'transport'],
      tsunami: ['wave', 'disaster', 'water'],
      tv: ['television', 'screen', 'monitor'],
      umbrella: ['rain', 'weather', 'protection'],
      union: ['combine', 'merge', 'together'],
      unlock: ['open', 'access', 'free'],
      upload: ['send', 'export', 'share'],
      usb: ['connector', 'port', 'device'],
      'vector-pen': ['design', 'draw', 'graphics'],
      vinyl: ['record', 'music', 'audio'],
      voicemail: ['message', 'audio', 'phone'],
      volume: ['sound', 'audio', 'speaker'],
      wallet: ['money', 'cards', 'finance'],
      watch: ['time', 'clock', 'wearable'],
      water: ['liquid', 'drink', 'blue'],
      wifi: ['wireless', 'internet', 'connection'],
      wind: ['air', 'breeze', 'weather'],
      window: ['glass', 'view', 'opening'],
      wrench: ['tool', 'fix', 'repair'],
      x: ['close', 'cancel', 'exit'],
      'yin-yang': ['balance', 'harmony', 'opposite'],
      zoom: ['magnify', 'scale', 'resize'],
    };

    for (const [key, values] of Object.entries(bootstrapSynonyms)) {
      if (iconName.includes(key)) {
        values.forEach((synonym) => tags.add(synonym));
      }
    }

    return Array.from(tags);
  }
}
