import { BaseNpmProvider } from './base-npm-provider.js';

/**
 * Feather Icons Provider
 *
 * Provides access to Feather Icons - simply beautiful open source icons
 * through NPM package integration.
 */
export class FeatherProvider extends BaseNpmProvider {
  constructor() {
    super('feather', 'Feather Icons', '4.29.1', 'feather-icons', ['dist/icons/*.svg'], ['regular']);
  }

  protected getDescription(): string {
    return 'Simply beautiful open source icons designed with a focus on simplicity, consistency, and flexibility.';
  }

  protected getSourceUrl(): string {
    return 'https://github.com/feathericons/feather';
  }

  protected getLicense(): string {
    return 'MIT';
  }

  /**
   * Override tag generation for Feather Icons specific patterns
   */
  protected generateTags(iconName: string): string[] {
    const tags = new Set(super.generateTags(iconName));

    // Add Feather specific tags
    tags.add('feather');
    tags.add('simple');
    tags.add('minimal');

    // Feather Icons specific synonyms
    const featherSynonyms: Record<string, string[]> = {
      activity: ['pulse', 'heartbeat', 'monitor'],
      airplay: ['cast', 'stream', 'wireless'],
      'alert-circle': ['warning', 'caution', 'error'],
      'alert-octagon': ['stop', 'warning', 'danger'],
      'alert-triangle': ['warning', 'caution', 'attention'],
      'align-center': ['text', 'center', 'middle'],
      'align-justify': ['text', 'justify', 'full'],
      'align-left': ['text', 'left', 'start'],
      'align-right': ['text', 'right', 'end'],
      anchor: ['link', 'chain', 'connection'],
      aperture: ['camera', 'lens', 'focus'],
      archive: ['box', 'storage', 'backup'],
      'arrow-down': ['download', 'south', 'bottom'],
      'arrow-left': ['back', 'previous', 'west'],
      'arrow-right': ['forward', 'next', 'east'],
      'arrow-up': ['upload', 'north', 'top'],
      'at-sign': ['email', 'mention', 'address'],
      award: ['trophy', 'prize', 'achievement'],
      'bar-chart': ['graph', 'statistics', 'data'],
      battery: ['power', 'energy', 'charge'],
      'bell-off': ['mute', 'silent', 'quiet'],
      bell: ['notification', 'alert', 'ring'],
      bluetooth: ['wireless', 'connection', 'device'],
      bold: ['text', 'strong', 'emphasis'],
      book: ['read', 'library', 'documentation'],
      bookmark: ['save', 'favorite', 'mark'],
      box: ['package', 'container', 'storage'],
      briefcase: ['work', 'business', 'job'],
      calendar: ['date', 'schedule', 'time'],
      camera: ['photo', 'picture', 'capture'],
      cast: ['airplay', 'stream', 'wireless'],
      'check-circle': ['done', 'complete', 'success'],
      'check-square': ['checkbox', 'done', 'complete'],
      check: ['tick', 'confirm', 'done'],
      'chevron-down': ['expand', 'dropdown', 'more'],
      'chevron-left': ['back', 'previous', 'west'],
      'chevron-right': ['forward', 'next', 'east'],
      'chevron-up': ['collapse', 'up', 'less'],
      'chevrons-down': ['expand', 'dropdown', 'more'],
      'chevrons-left': ['back', 'previous', 'west'],
      'chevrons-right': ['forward', 'next', 'east'],
      'chevrons-up': ['collapse', 'up', 'less'],
      chrome: ['browser', 'google', 'web'],
      circle: ['round', 'dot', 'shape'],
      clipboard: ['copy', 'paste', 'notes'],
      clock: ['time', 'schedule', 'timer'],
      'cloud-drizzle': ['rain', 'weather', 'light'],
      'cloud-lightning': ['storm', 'weather', 'thunder'],
      'cloud-off': ['offline', 'disconnected', 'no-cloud'],
      'cloud-rain': ['weather', 'precipitation', 'storm'],
      'cloud-snow': ['weather', 'winter', 'cold'],
      cloud: ['storage', 'sync', 'weather'],
      code: ['programming', 'development', 'script'],
      codepen: ['code', 'editor', 'development'],
      codesandbox: ['code', 'editor', 'development'],
      coffee: ['drink', 'beverage', 'caffeine'],
      columns: ['layout', 'grid', 'structure'],
      command: ['cmd', 'keyboard', 'shortcut'],
      compass: ['direction', 'navigation', 'guide'],
      copy: ['duplicate', 'clone', 'replicate'],
      'corner-down-left': ['arrow', 'turn', 'direction'],
      'corner-down-right': ['arrow', 'turn', 'direction'],
      'corner-left-down': ['arrow', 'turn', 'direction'],
      'corner-left-up': ['arrow', 'turn', 'direction'],
      'corner-right-down': ['arrow', 'turn', 'direction'],
      'corner-right-up': ['arrow', 'turn', 'direction'],
      'corner-up-left': ['arrow', 'turn', 'direction'],
      'corner-up-right': ['arrow', 'turn', 'direction'],
      cpu: ['processor', 'chip', 'computer'],
      'credit-card': ['payment', 'money', 'finance'],
      crop: ['image', 'edit', 'resize'],
      crosshair: ['target', 'aim', 'focus'],
      database: ['storage', 'data', 'server'],
      delete: ['remove', 'trash', 'bin'],
      disc: ['cd', 'dvd', 'storage'],
      'dollar-sign': ['money', 'currency', 'price'],
      download: ['save', 'import', 'get'],
      droplet: ['water', 'liquid', 'drop'],
      edit: ['modify', 'change', 'update'],
      'external-link': ['open', 'new-window', 'redirect'],
      'eye-off': ['hide', 'invisible', 'private'],
      eye: ['view', 'see', 'visibility'],
      facebook: ['social', 'network', 'share'],
      'fast-forward': ['skip', 'next', 'speed'],
      feather: ['icon', 'simple', 'minimal'],
      'file-minus': ['document', 'remove', 'delete'],
      'file-plus': ['document', 'add', 'create'],
      'file-text': ['document', 'text', 'paper'],
      file: ['document', 'paper', 'text'],
      film: ['movie', 'video', 'cinema'],
      filter: ['sort', 'organize', 'refine'],
      flag: ['marker', 'country', 'banner'],
      'folder-minus': ['directory', 'remove', 'delete'],
      'folder-plus': ['directory', 'add', 'create'],
      folder: ['directory', 'collection', 'group'],
      framer: ['design', 'prototype', 'tool'],
      frown: ['sad', 'unhappy', 'emotion'],
      gift: ['present', 'reward', 'bonus'],
      'git-branch': ['version', 'control', 'development'],
      'git-commit': ['version', 'control', 'development'],
      'git-merge': ['version', 'control', 'development'],
      'git-pull-request': ['version', 'control', 'development'],
      github: ['git', 'repository', 'code'],
      gitlab: ['git', 'repository', 'code'],
      globe: ['world', 'earth', 'international'],
      grid: ['layout', 'table', 'matrix'],
      'hard-drive': ['storage', 'disk', 'hdd'],
      hash: ['hashtag', 'number', 'pound'],
      headphones: ['audio', 'music', 'sound'],
      heart: ['love', 'like', 'favorite'],
      'help-circle': ['question', 'support', 'info'],
      hexagon: ['shape', 'geometry', 'six-sided'],
      home: ['house', 'main', 'start'],
      image: ['picture', 'photo', 'graphic'],
      inbox: ['mail', 'messages', 'receive'],
      info: ['information', 'help', 'about'],
      instagram: ['social', 'photo', 'sharing'],
      italic: ['text', 'emphasis', 'style'],
      key: ['password', 'security', 'access'],
      layers: ['stack', 'levels', 'depth'],
      layout: ['design', 'structure', 'arrangement'],
      'life-buoy': ['help', 'support', 'rescue'],
      link: ['chain', 'connect', 'url'],
      linkedin: ['social', 'professional', 'network'],
      list: ['items', 'menu', 'index'],
      loader: ['loading', 'spinner', 'wait'],
      lock: ['secure', 'private', 'protected'],
      'log-in': ['signin', 'enter', 'access'],
      'log-out': ['signout', 'exit', 'leave'],
      mail: ['email', 'message', 'letter'],
      'map-pin': ['location', 'marker', 'place'],
      map: ['location', 'navigation', 'geography'],
      'maximize-2': ['fullscreen', 'expand', 'large'],
      maximize: ['fullscreen', 'expand', 'large'],
      meh: ['neutral', 'emotion', 'face'],
      menu: ['hamburger', 'navigation', 'list'],
      'message-circle': ['chat', 'conversation', 'talk'],
      'message-square': ['chat', 'conversation', 'talk'],
      mic: ['microphone', 'voice', 'record'],
      'minimize-2': ['reduce', 'shrink', 'small'],
      minimize: ['reduce', 'shrink', 'small'],
      minus: ['subtract', 'remove', 'less'],
      monitor: ['screen', 'display', 'computer'],
      moon: ['night', 'dark', 'theme'],
      'more-horizontal': ['menu', 'options', 'dots'],
      'more-vertical': ['menu', 'options', 'dots'],
      'mouse-pointer': ['cursor', 'click', 'select'],
      move: ['drag', 'relocate', 'position'],
      music: ['audio', 'sound', 'song'],
      navigation: ['compass', 'direction', 'guide'],
      octagon: ['shape', 'stop', 'eight-sided'],
      package: ['box', 'delivery', 'shipping'],
      paperclip: ['attach', 'clip', 'link'],
      pause: ['stop', 'break', 'halt'],
      'pen-tool': ['design', 'draw', 'vector'],
      percent: ['percentage', 'ratio', 'proportion'],
      phone: ['call', 'telephone', 'mobile'],
      'pie-chart': ['graph', 'statistics', 'data'],
      'play-circle': ['start', 'begin', 'media'],
      play: ['start', 'begin', 'run'],
      plus: ['add', 'create', 'new'],
      pocket: ['save', 'bookmark', 'read-later'],
      power: ['on-off', 'electricity', 'energy'],
      printer: ['print', 'output', 'paper'],
      radio: ['broadcast', 'signal', 'audio'],
      'refresh-ccw': ['reload', 'update', 'sync'],
      'refresh-cw': ['reload', 'update', 'sync'],
      repeat: ['loop', 'cycle', 'again'],
      rewind: ['back', 'previous', 'reverse'],
      'rotate-ccw': ['turn', 'spin', 'counter-clockwise'],
      'rotate-cw': ['turn', 'spin', 'clockwise'],
      rss: ['feed', 'news', 'subscribe'],
      save: ['disk', 'store', 'keep'],
      scissors: ['cut', 'trim', 'clip'],
      search: ['find', 'look', 'magnify'],
      send: ['mail', 'message', 'deliver'],
      server: ['database', 'hosting', 'cloud'],
      settings: ['config', 'preferences', 'options'],
      share: ['distribute', 'send', 'export'],
      'shield-off': ['unprotected', 'vulnerable', 'insecure'],
      shield: ['security', 'protection', 'safe'],
      'shopping-bag': ['purchase', 'buy', 'store'],
      'shopping-cart': ['cart', 'buy', 'ecommerce'],
      shuffle: ['random', 'mix', 'rearrange'],
      sidebar: ['panel', 'navigation', 'menu'],
      'skip-back': ['previous', 'rewind', 'back'],
      'skip-forward': ['next', 'forward', 'skip'],
      slack: ['chat', 'team', 'communication'],
      slash: ['divide', 'separate', 'line'],
      sliders: ['controls', 'settings', 'adjust'],
      smartphone: ['phone', 'mobile', 'device'],
      smile: ['happy', 'joy', 'emotion'],
      speaker: ['audio', 'sound', 'volume'],
      square: ['shape', 'box', 'rectangle'],
      star: ['favorite', 'rating', 'bookmark'],
      'stop-circle': ['halt', 'pause', 'end'],
      sun: ['day', 'light', 'bright'],
      sunrise: ['morning', 'dawn', 'early'],
      sunset: ['evening', 'dusk', 'late'],
      tablet: ['device', 'mobile', 'screen'],
      tag: ['label', 'category', 'mark'],
      target: ['aim', 'goal', 'focus'],
      terminal: ['console', 'command', 'cli'],
      'thumbs-down': ['dislike', 'bad', 'negative'],
      'thumbs-up': ['like', 'good', 'positive'],
      'toggle-left': ['switch', 'off', 'disable'],
      'toggle-right': ['switch', 'on', 'enable'],
      tool: ['utility', 'repair', 'fix'],
      trash: ['delete', 'remove', 'bin'],
      'trending-down': ['decrease', 'falling', 'decline'],
      'trending-up': ['increase', 'rising', 'growth'],
      triangle: ['shape', 'three-sided', 'geometry'],
      truck: ['delivery', 'shipping', 'transport'],
      tv: ['television', 'screen', 'monitor'],
      twitch: ['streaming', 'gaming', 'live'],
      twitter: ['social', 'tweet', 'bird'],
      type: ['text', 'font', 'typography'],
      umbrella: ['rain', 'weather', 'protection'],
      underline: ['text', 'emphasis', 'style'],
      unlock: ['open', 'access', 'free'],
      upload: ['send', 'export', 'share'],
      user: ['person', 'profile', 'account'],
      'user-check': ['verified', 'approved', 'confirmed'],
      'user-minus': ['remove', 'delete', 'unfollow'],
      'user-plus': ['add', 'invite', 'follow'],
      'user-x': ['block', 'ban', 'remove'],
      users: ['people', 'team', 'group'],
      'video-off': ['camera-off', 'no-video', 'disabled'],
      video: ['camera', 'record', 'film'],
      voicemail: ['message', 'audio', 'phone'],
      'volume-1': ['sound', 'audio', 'low'],
      'volume-2': ['sound', 'audio', 'high'],
      'volume-x': ['mute', 'silent', 'quiet'],
      volume: ['sound', 'audio', 'speaker'],
      watch: ['time', 'clock', 'wearable'],
      wifi: ['wireless', 'internet', 'connection'],
      wind: ['air', 'breeze', 'weather'],
      'x-circle': ['close', 'cancel', 'remove'],
      'x-octagon': ['stop', 'cancel', 'block'],
      'x-square': ['close', 'cancel', 'remove'],
      x: ['close', 'cancel', 'exit'],
      youtube: ['video', 'streaming', 'watch'],
      'zap-off': ['no-power', 'disabled', 'inactive'],
      zap: ['lightning', 'fast', 'energy'],
      'zoom-in': ['magnify', 'enlarge', 'expand'],
      'zoom-out': ['reduce', 'shrink', 'minimize'],
    };

    for (const [key, values] of Object.entries(featherSynonyms)) {
      if (iconName.includes(key)) {
        values.forEach((synonym) => tags.add(synonym));
      }
    }

    return Array.from(tags);
  }
}
